services:
  application:
    container_name: sez_app
    build:
      context: ./sez
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./sez:/app
    working_dir: /app
    command: yarn dev
    env_file:
      - .env
    networks:
      - shaan-e-zaban

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOCALES=en,ur

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shaan-e-zaban

networks:
  shaan-e-zaban:


volumes:
  pgdata:
