services:
  backend:
    container_name: backend_sez
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go
    networks:
      - shaan-e-zaban

  frontend:
    container_name: frontend_sez
    build:
      context: ./frontend
    depends_on:
      - backend
      - json-server
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    env_file:
      - .env.local
    networks:
      - shaan-e-zaban

  json-server:
    container_name: json-server_sez
    image: clue/json-server
    depends_on:
      - backend
    ports:
      - "4000:80"
    volumes:
      - ./backend/content:/content
    command: >
      --watch /content/curriculum/${LEVEL}/${CEFR}/sentences.json
    environment:
      - LEVEL=Beginner
      - CEFR=A1
    networks:
      - shaan-e-zaban

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shaan-e-zaban

networks:
  shaan-e-zaban:

volumes:
  pgdata:
