services:
  backend:
    container_name: backend_shaan-e-zaban
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go
    networks:
      - shaan-e-zaban

  frontend:
    container_name: frontend_shaan-e-zaban
    build:
      context: ./frontend
    depends_on:
      - backend
      - json-server
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    environment:
      - NEXT_PUBLIC_API_URL=http://backend_shaan-e-zaban:8080
    networks:
      - shaan-e-zaban

  json-server:
    container_name: json-server_shaan-e-zaban
    image: clue/json-server
    depends_on:
      - backend
    ports:
      - "4000:80"
    volumes:
      - ./backend/data:/data
    command: --watch /data/urdu_sentences.json
    networks:
      - shaan-e-zaban

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: mein_khud
      POSTGRES_PASSWORD: chaiwalekapassword
      POSTGRES_DB: shaan_e_zaban_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shaan-e-zaban

networks:
  shaan-e-zaban:

volumes:
  pgdata:
